export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaloglu",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Joe Dane",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Cloe Saliba",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Lila Hernandez",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Susan Khoe",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Julien tane",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Gustavo Alan",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Marina Alcarez",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Manuela Zabada",
  },
];
export const Posts = [
  {
    id: 1,
    desc: "Love Foer All , Hatred For None",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 15,
  },
  {
    id: 2,

    photo: "assets/post/2.jpeg",
    date: "13 mins ago",
    userId: 2,
    like: 55,
    comment: 8,
  },
  {
    id: 3,
    desc: "Nature ❤️",
    photo: "assets/post/3.jpeg",
    date: "1 hours ago",
    userId: 3,
    like: 112,
    comment: 3,
  },
  {
    id: 5,
    desc: "Jour Inoubliable",
    photo: "assets/post/5.jpeg",
    date: "1h 30mins ago",
    userId: 5,
    like: 67,
    comment: 25,
  },
  {
    id: 6,
    // desc: "Love Foer All , Hatred For None",
    photo: "assets/post/6.jpeg",
    date: "2 hours ago",
    userId: 6,
    like: 30,
    comment: 5,
  },
  {
    id: 7,
    // desc: "Love Foer All , Hatred For None",
    photo: "assets/post/7.jpeg",
    date: "1 days ago",
    userId: 7,
    like: 32,
    comment: 15,
  },
  {
    id: 9,
    desc: "Love ❤️",
    photo: "assets/post/9.jpeg",
    date: "2 days  ago",
    userId: 9,
    like: 20,
    comment: 34,
  },
];
// export const Profiles = [
//   {
//     id: 1,
//     profilePicture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     desc: "Love Foer All , Hatred For None",
//     photo: "assets/post/1.jpeg",
//     date: "5 mins ago",
//     userId: 1,
//     like: 32,
//     comment: 15,
//   },
//   {
//     id: 1,
//     Picture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     desc: "Love Foer All , Hatred For None",
//     photo: "assets/post/1.jpeg",
//     date: "5 mins ago",
//     userId: 1,
//     like: 32,
//     comment: 15,
//   },
//   {
//     id: 1,
//     profilePicture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     desc: "Love Foer All , Hatred For None",
//     photo: "assets/post/1.jpeg",
//     date: "5 mins ago",
//     userId: 1,
//     like: 32,
//     comment: 15,
//   },
//   {
//     id: 1,
//     profilePicture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     photo: "assets/post/7.jpeg",
//     date: "5 mins ago",
//     userId: 1,
//     like: 32,
//     comment: 15,
//   },
//   {
//     id: 1,
//     profilePicture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     desc: "Love Foer All , Hatred For None",
//     photo: "assets/post/1.jpeg",
//     date: "15 mins ago",
//     userId: 1,
//     like: 32,
//     comment: 15,
//   },
//   {
//     id: 1,
//     profilePicture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     desc: "Love ❤️",
//     photo: "assets/post/9.jpeg",
//     date: "2 days  ago",
//     userId: 9,
//     like: 20,
//     comment: 34,
//   },
//   {
//     id: 1,
//     profilePicture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     desc: "so cute ❤️",
//     photo: "assets/post/6.jpeg",
//     date: "2 days  ago",
//     userId: 9,
//     like: 20,
//     comment: 34,
//   },
//   {
//     id: 1,
//     profilePicture: "assets/person/1.jpeg",
//     username: "Safak Kocaloglu",
//     desc: "F ocus in  my own projet ❤️",
//     photo: "assets/post/10.jpeg",
//     date: "2 days  ago",
//     userId: 9,
//     like: 20,
//     comment: 34,
//   },
// ];
